// const a =  selectedScores[0]+selectedScores[1]+selectedScores[2]                       
// const b =  selectedScores[3]+selectedScores[4]+selectedScores[5]
// const c =  selectedScores[6]+selectedScores[7]+selectedScores[8]
// const d = selectedScores[9]+selectedScores[10]+selectedScores[11]
// const e =  selectedScores[12]+selectedScores[13]+selectedScores[14]
// const f =  selectedScores[15]+selectedScores[16]+selectedScores[17]
