import blogimg_1 from '/Users/jeongjeyeong1/Documents/website/src/assets/blogimg_1.png'
import thumbsup from '/Users/jeongjeyeong1/Documents/website/src/assets/thumbs_up.png'
import share from '/Users/jeongjeyeong1/Documents/website/src/assets/share.png'

export const mockPosts = [
    {
      id: 1,
      title: "Blog Post 1",
      description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis …",
      imageUrl: blogimg_1,
      content: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.",
      overlayTopLine: "Top Line Text",
      overlayBottomLine: "Bottom Line Text",
      icon1Url: thumbsup,
      icon1Text: "1K",
      icon2Url: share,
      icon2Text: "1K",
      overlayImage: blogimg_1
    },
    {
      id: 2,
      title: "Blog Post 2",
      description: "Short description for post 2.",
      imageUrl: blogimg_1,
      content: "Full content for post 2.",
      overlayTopLine: "Top Line Text",
      overlayBottomLine: "Bottom Line Text",
      icon1Url: thumbsup,
      icon1Text: "1K",
      icon2Url: share,
      icon2Text: "1K",
      overlayImage: blogimg_1
    },
    {
        id: 3,
        title: "Blog Post 2",
        description: "Short description for post 2.",
        imageUrl: blogimg_1,
        content: "Full content for post 2.",
        overlayTopLine: "Top Line Text",
        overlayBottomLine: "Bottom Line Text",
        icon1Url: thumbsup,
        icon1Text: "1K",
        icon2Url: share,
        icon2Text: "1K",
        overlayImage: blogimg_1
      },
      {
        id: 4,
        title: "Blog Post 2",
        description: "Short description for post 2.",
        imageUrl: blogimg_1,
        content: "Full content for post 2.",
        overlayTopLine: "Top Line Text",
        overlayBottomLine: "Bottom Line Text",
        icon1Url: thumbsup,
        icon1Text: "1K",
        icon2Url: share,
        icon2Text: "1K",
        overlayImage: blogimg_1
      },
      {
        id: 5,
        title: "Blog Post 2",
        description: "Short description for post 2.",
        imageUrl: blogimg_1,
        content: "Full content for post 2.",
        overlayTopLine: "Top Line Text",
        overlayBottomLine: "Bottom Line Text",
        icon1Url: thumbsup,
        icon1Text: "1K",
        icon2Url: share,
        icon2Text: "1K",
        overlayImage: blogimg_1
      },
      {
        id: 6,
        title: "Blog Post 2",
        description: "Short description for post 2.",
        imageUrl: blogimg_1,
        content: "Full content for post 2.",
        overlayTopLine: "Top Line Text",
        overlayBottomLine: "Bottom Line Text",
        icon1Url: thumbsup,
        icon1Text: "1K",
        icon2Url: share,
        icon2Text: "1K",
        overlayImage: blogimg_1
      },
  ];

  export const questions = [
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",      
    "I like yoda",
    "I am curious about the unknown.",
    "I often find myself questioning conventional beliefs",   
  ];